export const states = [
  {
    sectors: "Construction",
    current_allocation: 105000000,
    previous_allocation: 400000000,
    alias: "construction",
    projects: [
      "Residential High-Rise Development",
      "Infrastructure Rehabilitation",
      "Commercial Complex Construction",
      "Sports Stadium Construction",
    ],
  },
  {
    sectors: "Education",
    current_allocation: 74800000,
    previous_allocation: 850000000,
    alias: "education",
    projects: [
      "National Digital Learning Initiative",
      "Education for All Program",
      "STEM Education Expansion Project",
      "School Infrastructure Development Scheme",
    ],
  },
  {
    sectors: "Agriculture",
    current_allocation: 71000000,
    previous_allocation: 550000000,
    alias: "agriculture",
    projects: [
      "Farm Modernization and Mechanization Program",
      "Rural Agricultural Development Initiative",
      "Crop Diversification and Market Expansion Project",
      "Sustainable Irrigation and Water Management Scheme",
    ],
  },
  {
    sectors: "Mining & Extraction",
    current_allocation: 120000000,
    previous_allocation: 300000000,
    alias: "mining & extraction",
    projects: [
      "Mineral Resource Exploration and Development Program",
      "Mining Infrastructure Upgrading Project",
      "Environmental Management and Rehabilitation of Mining Sites Initiative",
      "Mineral Processing and Value Addition Scheme",
      "Geological Survey and Mapping Enhancement Program",
    ],
  },
  {
    sectors: "Manufacturing",
    current_allocation: 300000000,
    previous_allocation: 560000000,
    alias: "manufacturing",
    projects: [
      "Advanced Manufacturing Technology Adoption Initiative",
      "Export Promotion Program for Manufacturing Industries",
      "Industrial Park Development and Expansion Project",
    ],
  },
  {
    sectors: "Banking & Health",
    current_allocation: 974000000,
    previous_allocation: 30000000,
    alias: "banking & health",
    projects: [
      "Financial Inclusion and Healthcare Access Program",
      "Healthcare Infrastructure Modernization Project",
      "Digital Banking Transformation Initiative",
      "Health Insurance Coverage Expansion Scheme",
      "National Healthcare Data Integration Project",
    ],
  },
  {
    sectors: "Energy & Utilities",
    current_allocation: 522000000,
    previous_allocation: 310000000,
    alias: "energy and utilities",
    projects: [
      "National Renewable Energy Development Program",
      "Smart Grid Modernization Initiative",
      "Rural Electrification and Energy Efficiency Project",
    ],
  },
  {
    sectors: "Financial Services",
    current_allocation: 605000000,
    previous_allocation: 851000000,
    alias: "financial services",
    projects: [
      "Financial Inclusion for Rural Communities Program",
      "National Digital Payments Initiative",
      "SME Financing and Credit Guarantee Scheme",
      "Financial Literacy and Education Campaign",
      "Digital Banking Infrastructure Development Project",
    ],
  },
  {
    sectors: "Information Technology and Communication",
    current_allocation: 652000000,
    previous_allocation: 423000000,
    alias: "information technology and communication",
    projects: [
      "National Broadband Connectivity Program",
      "E-Government Services Enhancement Project",
      "Cybersecurity and Data Protection Initiative",
      "Digital Skills Training and Employment Program",
      "Smart Cities Technology Integration Scheme",
    ],
  },
];
